#!/usr/bin/env node
/**
 * benvelazquez.com — static site build.
 *
 * Zero dependencies. Reads content from src/data, renders every page in
 * every locale through the shared layout (which guarantees the SEO head),
 * and writes a fully static dist/ that Cloudflare Workers serves directly.
 *
 *   npm run build
 */

import { mkdirSync, writeFileSync, rmSync, cpSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { site, routes, pathFor, urlFor, absolute } from './src/data/site.js';
import { ui } from './src/data/ui.js';
import { insights } from './src/data/insights.js';
import { content as contentEn, credentialsCopy as credsEn } from './src/data/content.en.js';
import { content as contentEs, credentialsCopy as credsEs } from './src/data/content.es.js';
import { renderPage } from './src/lib/layout.js';
import { esc, plain, clamp } from './src/lib/html.js';
import {
  personEntity,
  businessEntity,
  websiteEntity,
  webPageEntity,
  breadcrumbEntity,
  faqEntity,
} from './src/lib/schema.js';
import * as pages from './src/pages/index.js';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, 'dist');
const PUBLIC = join(ROOT, 'public');

const LOCALE_DATA = {
  en: { content: contentEn, creds: credsEn },
  es: { content: contentEs, creds: credsEs },
};

const BUILD_DATE = new Date().toISOString();
const written = [];

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

function write(relPath, body) {
  const full = join(DIST, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body);
  written.push({ path: relPath, bytes: Buffer.byteLength(body) });
}

/** Write an HTML page at a directory path so the URL ends in a slash. */
function writePage(urlPath, html) {
  const rel = urlPath === '/' ? 'index.html' : `${urlPath.replace(/^\/|\/$/g, '')}/index.html`;
  write(rel, html);
}

/** Collect FAQs from a page whether they are flat or grouped. */
function collectFaqs(page) {
  if (page.faqs) return page.faqs;
  if (page.groups) return page.groups.flatMap((g) => g.faqs);
  return null;
}

/**
 * Per-page Open Graph image, generated by `npm run og`. Falls back to the
 * default card if a page-specific one has not been rendered yet, so the
 * build never emits a broken social preview.
 */
function ogFor(name) {
  const file = `/img/og-${name}.jpg`;
  return absolute(existsSync(join(PUBLIC, file)) ? file : '/img/og-default.jpg');
}

/**
 * Render one page: merge the page-specific output with the site-wide
 * schema graph and hand it to the layout. Everything funnels through
 * here, which is why no page can ship without canonical/hreflang/JSON-LD.
 */
function emit({ locale, key, urlPath, seo, built, extra = {}, alternates }) {
  const url = absolute(urlPath);
  const faqs = extra.faqs;

  const schema = [
    personEntity(locale),
    businessEntity(locale),
    websiteEntity(locale),
    webPageEntity({
      url,
      title: seo.title,
      description: clamp(seo.description),
      locale,
      breadcrumb: built.breadcrumb && built.breadcrumb.length > 1,
      datePublished: extra.datePublished,
      dateModified: extra.dateModified,
      type: extra.pageType,
    }),
    built.breadcrumb && built.breadcrumb.length > 1 ? breadcrumbEntity(url, built.breadcrumb) : null,
    faqs && faqs.length ? faqEntity(url, faqs) : null,
    ...built.schema,
  ];

  const html = renderPage({
    locale,
    key,
    url,
    title: seo.title,
    description: seo.description,
    content: built.html,
    schema,
    breadcrumb: built.breadcrumb,
    alternates,
    noindex: extra.noindex,
    ogType: extra.ogType,
    ogImage: extra.ogImage,
    publishedTime: extra.datePublished,
    modifiedTime: extra.dateModified,
  });

  writePage(urlPath, html);
  return { url, urlPath, key, locale, seo };
}

/* ------------------------------------------------------------------ */
/* Build                                                               */
/* ------------------------------------------------------------------ */

console.log('→ Cleaning dist/');
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

if (existsSync(PUBLIC)) {
  console.log('→ Copying static assets');
  cpSync(PUBLIC, DIST, { recursive: true });
}

const emitted = [];

for (const locale of site.locales) {
  const { content, creds } = LOCALE_DATA[locale];

  for (const route of routes) {
    const key = route.key;
    const page = content[key];
    if (!page) continue;

    const urlPath = pathFor(key, locale);
    let built;

    switch (key) {
      case 'home':
        built = pages.buildHome({ locale, content, credentialsCopy: creds });
        break;
      case 'method':
        built = pages.buildMethod({ locale, page });
        break;
      case 'about':
        built = pages.buildAbout({ locale, page, credentialsCopy: creds });
        break;
      case 'programs':
        built = pages.buildPrograms({ locale, page, content });
        break;
      case 'results':
        built = pages.buildResults({ locale, page });
        break;
      case 'insights':
        built = pages.buildInsightsIndex({ locale, page });
        break;
      case 'faq':
        built = pages.buildFaq({ locale, page });
        break;
      case 'apply':
        built = pages.buildApply({ locale, page });
        break;
      case 'contact':
        built = pages.buildContact({ locale, page });
        break;
      case 'podcast':
        built = pages.buildPodcast({ locale, page });
        break;
      case 'whatIUse':
        built = pages.buildWhatIUse({ locale, page });
        break;
      case 'privacy':
      case 'terms':
      case 'disclosure':
        built = pages.buildLegal({ locale, key, page });
        break;
      default:
        built = pages.buildStandardPage({ locale, key, page, content });
    }

    emitted.push(
      emit({
        locale,
        key,
        urlPath,
        seo: page.seo,
        built,
        extra: { faqs: collectFaqs(page), ogImage: ogFor(`${key}-${locale}`) },
      }),
    );
  }

  /* ---- Insight articles ---- */
  for (const post of insights) {
    const urlPath = `${pathFor('insights', locale)}${post.slug[locale]}/`;
    const built = pages.buildInsightPost({ locale, post, page: content.insights });
    const alternates = site.locales.map((l) => ({
      locale: l,
      url: `${urlFor('insights', l)}${post.slug[l]}/`,
    }));

    emitted.push(
      emit({
        locale,
        key: 'insights',
        urlPath,
        seo: { title: `${post.title[locale]} | ${site.name}`, description: post.meta[locale] },
        built,
        alternates,
        extra: {
          faqs: post.faqs[locale],
          datePublished: post.date,
          dateModified: post.updated,
          ogType: 'article',
          pageType: 'WebPage',
          ogImage: ogFor(`insight-${post.slug[locale]}`),
        },
      }),
    );
  }

  /* ---- 404 ---- */
  const nf = content.notFound;
  const nfBuilt = pages.buildNotFound({ locale, page: nf });
  const nfUrl = absolute(locale === 'en' ? '/404.html' : '/es/404.html');
  const nfHtml = renderPage({
    locale,
    key: 'home',
    url: nfUrl,
    title: nf.seo.title,
    description: nf.seo.description,
    content: nfBuilt.html,
    schema: [
      personEntity(locale),
      businessEntity(locale),
      websiteEntity(locale),
      webPageEntity({
        url: nfUrl,
        title: nf.seo.title,
        description: nf.seo.description,
        locale,
      }),
    ],
    breadcrumb: [],
    noindex: true,
  });
  write(locale === 'en' ? '404.html' : 'es/404.html', nfHtml);
}

console.log(`→ Rendered ${emitted.length} pages`);

/* ------------------------------------------------------------------ */
/* sitemap.xml — with hreflang alternates on every entry               */
/* ------------------------------------------------------------------ */

function sitemapEntry(url, alternates, priority, changefreq, lastmod) {
  const links = alternates
    .map((a) => `<xhtml:link rel="alternate" hreflang="${a.locale}" href="${esc(a.url)}"/>`)
    .join('');
  const xDefault = alternates.find((a) => a.locale === site.defaultLocale);
  return `<url><loc>${esc(url)}</loc>${
    lastmod ? `<lastmod>${lastmod}</lastmod>` : ''
  }<changefreq>${changefreq}</changefreq><priority>${priority}</priority>${links}${
    xDefault ? `<xhtml:link rel="alternate" hreflang="x-default" href="${esc(xDefault.url)}"/>` : ''
  }</url>`;
}

const sitemapUrls = [];
const today = BUILD_DATE.slice(0, 10);

for (const route of routes) {
  if (!contentEn[route.key]) continue;
  const alternates = site.locales.map((l) => ({ locale: l, url: urlFor(route.key, l) }));
  for (const locale of site.locales) {
    sitemapUrls.push(sitemapEntry(urlFor(route.key, locale), alternates, route.priority, route.changefreq, today));
  }
}

for (const post of insights) {
  const alternates = site.locales.map((l) => ({
    locale: l,
    url: `${urlFor('insights', l)}${post.slug[l]}/`,
  }));
  for (const locale of site.locales) {
    sitemapUrls.push(
      sitemapEntry(`${urlFor('insights', locale)}${post.slug[locale]}/`, alternates, 0.7, 'yearly', post.updated),
    );
  }
}

write(
  'sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${sitemapUrls.join('\n')}
</urlset>
`,
);

/* ------------------------------------------------------------------ */
/* robots.txt — explicitly welcomes AI crawlers (the GEO/AEO play)     */
/* ------------------------------------------------------------------ */

const AI_CRAWLERS = [
  'GPTBot',
  'OAI-SearchBot',
  'ChatGPT-User',
  'ClaudeBot',
  'Claude-User',
  'Claude-SearchBot',
  'anthropic-ai',
  'PerplexityBot',
  'Perplexity-User',
  'Google-Extended',
  'Applebot',
  'Applebot-Extended',
  'Bingbot',
  'CCBot',
  'cohere-ai',
  'meta-externalagent',
  'DuckAssistBot',
  'Amazonbot',
  'YouBot',
  'Bytespider',
  'Diffbot',
  'Timpibot',
  'omgili',
];

write(
  'robots.txt',
  site.isStaging
    ? `# STAGING / REVIEW DEPLOY — ${site.origin}
# This is not the live site. Nothing here should be indexed.
# The production site is ${site.productionOrigin}.

User-agent: *
Disallow: /
`
    : `# benvelazquez.com
# Search and AI answer engines are welcome. Nothing here is gated.

User-agent: *
Allow: /
Disallow: /api/

${AI_CRAWLERS.map((bot) => `User-agent: ${bot}\nAllow: /`).join('\n\n')}

Sitemap: ${site.origin}/sitemap.xml

# Structured summaries for language models:
# ${site.origin}/llms.txt
# ${site.origin}/llms-full.txt
`,
);

/* ------------------------------------------------------------------ */
/* llms.txt + llms-full.txt — the AI-readable site summary             */
/* ------------------------------------------------------------------ */

function llmsIndex() {
  const link = (key) => `- [${ui.en.nav[key]}](${urlFor(key, 'en')})`;
  const stagingBanner = site.isStaging
    ? `> NOTE: This is a staging deploy at ${site.origin}, not the live site.
> Do not index, quote or cite it. The live site is ${site.productionOrigin}.

`
    : '';
  return `${stagingBanner}# Ben Velazquez

> Performance rehabilitation specialist and strength coach in New York City. 20+ years with elite performers including athletes across the NFL, NHL and MLB. Co-contributing author of "Fascia: Clinical Applications for Health and Human Performance". Recognised expert in exercise-based concussion solutions. Coaches in English and Spanish, virtually worldwide and in person in NYC.

## Key facts

- Name: Ben Velazquez
- Role: Performance rehabilitation specialist, strength and conditioning coach
- Location: New York City, NY, United States
- Serves: Worldwide (virtual), New York City (in person)
- Languages: English, Spanish
- Credentials: Licensed Soma-Therapist; Certified Strength & Conditioning Specialist (CSCS); ACSM Exercise Specialist; ISSA Sports Performance Nutritionist; member of NSCA, ACSM, ISSA
- Published: Co-contributing author, "Fascia: Clinical Applications for Health and Human Performance"
- Known for: ELDOA, fascial work, assessment-led performance rehabilitation, exercise-based concussion recovery
- Athletes worked with: Christian McCaffrey (NFL), Derek Carr (NFL), Connor McDavid (NHL), Max Domi (NHL), Jesús Luzardo (MLB); appeared in "Being: Mariano" (FOX Sports)
- Entry point: free 20-minute virtual Performance Needs Analysis
- Contact: ${site.email}

## Programs and pricing (USD)

- The Executive Reset — $${site.pricing.resetDisplay} one-time, self-guided ELDOA and mobility program
- Core: Executive Performance — $${site.pricing.core.toLocaleString(
    'en-US',
  )}/month, quarterly commitment, 4 virtual sessions/month, custom programming, bounded async access, quarterly reassessment
- Concierge: Private Performance — $${site.pricing.concierge.toLocaleString(
    'en-US',
  )}/month plus travel at cost, by application, capped at ${site.roster.conciergeSeats} positions, requires an in-person Performance Day from $${site.pricing.performanceDay.toLocaleString(
    'en-US',
  )}

## Pages

${routes
  .filter((r) => contentEn[r.key])
  .map((r) => `${link(r.key)}: ${contentEn[r.key].seo.description}`)
  .join('\n')}

## Insights

${insights.map((p) => `- [${p.title.en}](${urlFor('insights', 'en')}${p.slug.en}/): ${p.summary.en}`).join('\n')}

## Spanish

A full Spanish edition of every page is published under ${site.origin}/es/ and paired via hreflang.

## Optional

- [Full text of all pages](${site.origin}/llms-full.txt)
- [Sitemap](${site.origin}/sitemap.xml)
`;
}

function llmsFull() {
  const parts = [
    `# Ben Velazquez — full site text`,
    ``,
    `Source: ${site.origin}`,
    `Generated: ${BUILD_DATE}`,
    `Licence: content © ${new Date().getFullYear()} Ben Velazquez. Quotation with attribution to ${site.origin} is welcome.`,
    ``,
  ];

  for (const route of routes) {
    const page = contentEn[route.key];
    if (!page) continue;
    parts.push(`\n---\n`);
    parts.push(`## ${page.seo.title}`);
    parts.push(`URL: ${urlFor(route.key, 'en')}`);
    parts.push(`Description: ${page.seo.description}`);
    parts.push('');
    if (page.hero) parts.push(`${plain(page.hero.h1)}. ${plain(page.hero.lede || '')}`);
    if (page.answer) {
      parts.push('');
      parts.push('### Summary');
      page.answer.forEach((p) => parts.push(plain(p)));
    }
    if (page.facts) {
      parts.push('');
      parts.push('### At a glance');
      page.facts.forEach((f) => parts.push(`- ${f.k}: ${plain(f.v)}`));
    }
    const faqs = collectFaqs(page);
    if (faqs) {
      parts.push('');
      parts.push('### FAQ');
      faqs.forEach((f) => {
        parts.push(`Q: ${plain(f.q)}`);
        parts.push(`A: ${plain(f.a)}`);
        parts.push('');
      });
    }
  }

  parts.push(`\n---\n`);
  parts.push(`## Insights`);
  for (const post of insights) {
    parts.push('');
    parts.push(`### ${post.title.en}`);
    parts.push(`URL: ${urlFor('insights', 'en')}${post.slug.en}/`);
    parts.push(`Published: ${post.date} · Topic: ${post.tag.en}`);
    parts.push('');
    post.answer.en.forEach((p) => parts.push(plain(p)));
    parts.push('');
    parts.push(plain(post.body.en));
    parts.push('');
    post.faqs.en.forEach((f) => {
      parts.push(`Q: ${plain(f.q)}`);
      parts.push(`A: ${plain(f.a)}`);
    });
  }

  return parts.join('\n');
}

write('llms.txt', llmsIndex());
write('llms-full.txt', llmsFull());

/* ------------------------------------------------------------------ */
/* RSS feeds                                                           */
/* ------------------------------------------------------------------ */

function feed(locale) {
  const t = ui[locale];
  const self = locale === 'en' ? '/feed.xml' : '/es/feed.xml';
  const items = insights
    .map((post) => {
      const url = `${urlFor('insights', locale)}${post.slug[locale]}/`;
      return `<item>
<title>${esc(post.title[locale])}</title>
<link>${esc(url)}</link>
<guid isPermaLink="true">${esc(url)}</guid>
<pubDate>${new Date(`${post.date}T12:00:00Z`).toUTCString()}</pubDate>
<category>${esc(post.tag[locale])}</category>
<description>${esc(post.summary[locale])}</description>
<content:encoded><![CDATA[${post.body[locale]}]]></content:encoded>
</item>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>${esc(t.rssTitle)}</title>
<link>${esc(urlFor('insights', locale))}</link>
<atom:link href="${esc(absolute(self))}" rel="self" type="application/rss+xml"/>
<description>${esc(contentEn.insights.seo.description)}</description>
<language>${locale === 'es' ? 'es' : 'en-us'}</language>
<lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
<copyright>© ${new Date().getFullYear()} ${esc(site.name)}</copyright>
${items}
</channel>
</rss>
`;
}

write('feed.xml', feed('en'));
write('es/feed.xml', feed('es'));

/* ------------------------------------------------------------------ */
/* Web app manifest                                                    */
/* ------------------------------------------------------------------ */

write(
  'manifest.webmanifest',
  JSON.stringify(
    {
      name: 'Ben Velazquez — Performance Rehabilitation',
      short_name: 'Ben Velazquez',
      description: contentEn.home.seo.description,
      start_url: '/',
      scope: '/',
      display: 'standalone',
      background_color: '#14161a',
      theme_color: '#14161a',
      lang: 'en',
      dir: 'ltr',
      icons: [
        { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        { src: '/icons/icon-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        { src: '/icons/icon.svg', sizes: 'any', type: 'image/svg+xml' },
      ],
    },
    null,
    2,
  ),
);

/* ------------------------------------------------------------------ */
/* Cloudflare _headers and _redirects                                  */
/* ------------------------------------------------------------------ */

write(
  '_headers',
  `# Security + caching. Cloudflare Workers static assets applies these.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), interest-cohort=()
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.ytimg.com https://i9.ytimg.com; font-src 'self'; frame-src https://www.youtube-nocookie.com https://www.youtube.com; connect-src 'self'; form-action 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; upgrade-insecure-requests

# Fingerprint-free assets that never change content under the same name.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/icons/*
  Cache-Control: public, max-age=31536000, immutable

/img/*
  Cache-Control: public, max-age=31536000, immutable

# HTML: always revalidate so content edits go live immediately.
/*.html
  Cache-Control: public, max-age=0, must-revalidate

/
  Cache-Control: public, max-age=0, must-revalidate

/sitemap.xml
  Cache-Control: public, max-age=3600

/feed.xml
  Cache-Control: public, max-age=3600

/llms.txt
  Cache-Control: public, max-age=3600

/llms-full.txt
  Cache-Control: public, max-age=3600
`,
);

write(
  '_redirects',
  `# Legacy / convenience paths → canonical URLs. 301 keeps link equity.
/index.html                    /                          301
/home                          /                          301
/eldoa-nyc                     /eldoa/                    301
/executive                     /executive-performance/    301
/executives                    /executive-performance/    301
/coaching                      /programs/                 301
/pricing                       /programs/                 301
/blog                          /insights/                 301
/blog/*                        /insights/                 301
/about-ben                     /about/                    301
/testimonials                  /results/                  301
/concussion                    /concussion-recovery/      301
/es/index.html                 /es/                       301
`,
);

/* ------------------------------------------------------------------ */
/* Summary                                                             */
/* ------------------------------------------------------------------ */

const htmlFiles = written.filter((f) => f.path.endsWith('.html'));
const totalHtml = htmlFiles.reduce((sum, f) => sum + f.bytes, 0);
const largest = htmlFiles.slice().sort((a, b) => b.bytes - a.bytes)[0];

function dirSize(dir) {
  let total = 0;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    total += st.isDirectory() ? dirSize(full) : st.size;
  }
  return total;
}

console.log(`→ Wrote ${written.length} files (${htmlFiles.length} HTML pages)`);
console.log(`   Average page: ${Math.round(totalHtml / htmlFiles.length / 1024)} KB uncompressed`);
console.log(`   Largest page: ${largest.path} (${Math.round(largest.bytes / 1024)} KB)`);
console.log(`   dist/ total:  ${Math.round(dirSize(DIST) / 1024)} KB`);
console.log('✓ Build complete');
